/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
      "./app/**/*.{js,ts,jsx,tsx,mdx}",
      "./components/**/*.{js,ts,jsx,tsx,mdx}",
      // add other relevant paths
    ],
    theme: {
      extend: {
        colors: {
          primary: 'var(--bg-primary)',
          secondary: 'var(--bg-secondary)',
          accent: 'var(--accent-color)',
          'accent-hover': 'var(--accent-hover)',
          'text-primary': 'var(--text-primary)',
          'text-secondary': 'var(--text-secondary)',
          'border-color': 'var(--border-color)',
          'code-bg': 'var(--code-bg)',
          'code-text': 'var(--code-text)',
          'pre-bg': 'var(--pre-bg)',
          'pre-text': 'var(--pre-text)',
        },
        typography: {
          DEFAULT: {
            css: {
              color: 'var(--text-primary)',
              maxWidth: 'none',
              fontSize: '1rem',
              lineHeight: '1.75',
              '--tw-prose-body': 'var(--text-primary)',
              '--tw-prose-headings': 'var(--text-primary)',
              '--tw-prose-links': 'var(--accent-color)',
              '--tw-prose-bold': 'var(--text-primary)',
              '--tw-prose-counters': 'var(--text-secondary)',
              '--tw-prose-bullets': 'var(--border-color)',
              '--tw-prose-hr': 'var(--border-color)',
              '--tw-prose-quotes': 'var(--text-secondary)',
              '--tw-prose-quote-borders': 'var(--border-color)',
              '--tw-prose-captions': 'var(--text-secondary)',
              '--tw-prose-code': 'var(--code-text)',
              '--tw-prose-pre-code': 'var(--pre-text)',
              '--tw-prose-pre-bg': 'var(--pre-bg)',
              '--tw-prose-th-borders': 'var(--border-color)',
              '--tw-prose-td-borders': 'var(--border-color)',
              a: {
                color: 'var(--accent-color)',
                textDecoration: 'underline',
                fontWeight: '500',
                '&:hover': {
                  color: 'var(--accent-hover)',
                },
              },
              h1: {
                color: 'var(--text-primary)',
                fontWeight: '700',
                fontSize: '2.25rem',
                marginTop: '0',
                marginBottom: '0.8888889em',
                lineHeight: '1.1111111',
              },
              h2: {
                color: 'var(--text-primary)',
                fontWeight: '600',
                fontSize: '1.5rem',
                marginTop: '2em',
                marginBottom: '1em',
                lineHeight: '1.3333333',
              },
              h3: {
                color: 'var(--text-primary)',
                fontWeight: '600',
                fontSize: '1.25rem',
                marginTop: '1.6em',
                marginBottom: '0.6em',
                lineHeight: '1.6',
              },
              h4: {
                color: 'var(--text-primary)',
                fontWeight: '600',
              },
              h5: {
                color: 'var(--text-primary)',
                fontWeight: '600',
              },
              h6: {
                color: 'var(--text-primary)',
                fontWeight: '600',
              },
              p: {
                color: 'var(--text-primary)',
                marginTop: '1.25em',
                marginBottom: '1.25em',
              },
              strong: {
                color: 'var(--text-primary)',
                fontWeight: '600',
              },
              code: {
                color: 'var(--code-text)',
                fontWeight: '600',
                fontSize: '0.875em',
                backgroundColor: 'var(--code-bg)',
                padding: '2px 4px',
                borderRadius: '4px',
              },
              'code::before': {
                content: '""',
              },
              'code::after': {
                content: '""',
              },
              pre: {
                color: 'var(--pre-text)',
                backgroundColor: 'var(--pre-bg)',
                overflowX: 'auto',
                fontWeight: '400',
                fontSize: '0.875em',
                lineHeight: '1.7142857',
                marginTop: '1.7142857em',
                marginBottom: '1.7142857em',
                borderRadius: '0.375rem',
                paddingTop: '0.8571429em',
                paddingRight: '1.1428571em',
                paddingBottom: '0.8571429em',
                paddingLeft: '1.1428571em',
              },
              'pre code': {
                backgroundColor: 'transparent',
                borderWidth: '0',
                borderRadius: '0',
                padding: '0',
                fontWeight: 'inherit',
                color: 'inherit',
                fontSize: 'inherit',
                fontFamily: 'inherit',
                lineHeight: 'inherit',
              },
              blockquote: {
                fontWeight: '500',
                fontStyle: 'italic',
                color: 'var(--text-secondary)',
                borderLeftWidth: '0.25rem',
                borderLeftColor: 'var(--accent-color)',
                quotes: '"\\201C""\\201D""\\2018""\\2019"',
                marginTop: '1.6em',
                marginBottom: '1.6em',
                paddingLeft: '1em',
              },
              table: {
                width: '100%',
                tableLayout: 'auto',
                textAlign: 'left',
                marginTop: '2em',
                marginBottom: '2em',
              },
              thead: {
                color: 'var(--text-primary)',
                fontWeight: '600',
                borderBottomWidth: '1px',
                borderBottomColor: 'var(--border-color)',
              },
              'thead th': {
                verticalAlign: 'bottom',
                paddingRight: '0.5714286em',
                paddingBottom: '0.5714286em',
                paddingLeft: '0.5714286em',
              },
              'tbody tr': {
                borderBottomWidth: '1px',
                borderBottomColor: 'var(--border-color)',
              },
              'tbody tr:last-child': {
                borderBottomWidth: '0',
              },
              'tbody td': {
                verticalAlign: 'baseline',
                paddingTop: '0.5714286em',
                paddingRight: '0.5714286em',
                paddingBottom: '0.5714286em',
                paddingLeft: '0.5714286em',
                color: 'var(--text-primary)',
              },
              'tbody th': {
                color: 'var(--text-primary)',
                verticalAlign: 'baseline',
                paddingTop: '0.5714286em',
                paddingRight: '0.5714286em',
                paddingBottom: '0.5714286em',
                paddingLeft: '0.5714286em',
              },
              li: {
                color: 'var(--text-primary)',
                marginTop: '0.5em',
                marginBottom: '0.5em',
              },
              'li > ul': {
                marginTop: '0.75em',
                marginBottom: '0.75em',
              },
              'li > ol': {
                marginTop: '0.75em',
                marginBottom: '0.75em',
              },
            },
          },
        },
      },
    },
    plugins: [require('@tailwindcss/typography')],
  }